version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # hot reload if you edit code locally
    environment:
      - FLASK_ENV=development  # enables debug mode
